version: "3"
services:
  inventory:
    container_name: inventory
    build:
      context: .
      dockerfile: release/Dockerfile
    ports:
      - "15888:15888"
    volumes:
      - /Users/davidcheah/Desktop/DavidCheah/Golang/inventory/inventory/server/log:/var/log/app-log
    networks:
      - backend
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
networks:
  backend:

volumes:
  mongodb_data_container:
