log-directory = "/var/log/app-log"

[services]
	[inventory-service]
		name = "inventory"
		host = "0.0.0.0"
		port = 15888
		log-file-name = "inventory.log"
[mongodb]
	url = "mongodb://13.212.8.178:27017"